// Copyright 2018 Ulf Adams
//
// The contents of this file may be used under the terms of the Apache License,
// Version 2.0.
//
//    (See accompanying file LICENSE-Apache or copy at
//     http://www.apache.org/licenses/LICENSE-2.0)
//
// Alternatively, the contents of this file may be used under the terms of
// the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE-Boost or copy at
//     https://www.boost.org/LICENSE_1_0.txt)
//
// Unless required by applicable law or agreed to in writing, this software
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.
#ifndef RYU_HH_
#define RYU_HH_

#include <cassert>
#include <cinttypes>
#include <cstring>
#include <cmath>

#include <nih/logging.hh>
#include <nih/luts.hh>

namespace nih {

struct UnsignedFloatBase2 {
  uint32_t mantissa;
  // Decimal exponent's range is -45 to 38
  // inclusive, and can fit in a short if needed.
  uint32_t exponent;
};

struct UnsignedFloatBase10 {
  uint32_t mantissa;
  // Decimal exponent's range is -45 to 38
  // inclusive, and can fit in a short if needed.
  int32_t exponent;
};

struct IEEE754 {
  static constexpr uint32_t kFloatMantissaBits = 23;
  static constexpr uint32_t kFloatBias = 127;
  static constexpr uint32_t kFloatExponentBits = 8;

  static void Decode(float f, UnsignedFloatBase2* uf, bool* signbit) {
    uint32_t bits;
    std::memcpy(&bits, &f, sizeof(bits));
    // Decode bits into sign, mantissa, and exponent.
    *signbit = std::signbit(f);
    uf->mantissa = bits & ((1u << kFloatMantissaBits) - 1);
    uf->exponent = (bits >> IEEE754::kFloatMantissaBits) &
                   ((1u << IEEE754::kFloatExponentBits) - 1);
  }
};

static inline int
SpecialStr(char *const result, const bool sign, const bool exponent,
           const bool mantissa) {
  if (mantissa) {
    std::memcpy(result, "NaN", 3);
    return 3;
  }
  if (sign) {
    result[0] = '-';
  }
  if (exponent) {
    std::memcpy(result + sign, "Infinity", 8);
    return sign + 8;
  }
  std::memcpy(result + sign, "0E0", 3);
  return sign + 3;
}

struct PowerBaseComputer {
  // This table is generated by PrintFloatLookupTable.
  uint32_t constexpr static kFloatPow5InvBitcount = 59;
  static constexpr uint64_t kFloatPow5InvSplit[31] = {
      576460752303423489u, 461168601842738791u, 368934881474191033u,
      295147905179352826u, 472236648286964522u, 377789318629571618u,
      302231454903657294u, 483570327845851670u, 386856262276681336u,
      309485009821345069u, 495176015714152110u, 396140812571321688u,
      316912650057057351u, 507060240091291761u, 405648192073033409u,
      324518553658426727u, 519229685853482763u, 415383748682786211u,
      332306998946228969u, 531691198313966350u, 425352958651173080u,
      340282366920938464u, 544451787073501542u, 435561429658801234u,
      348449143727040987u, 557518629963265579u, 446014903970612463u,
      356811923176489971u, 570899077082383953u, 456719261665907162u,
      365375409332725730u};

  uint32_t constexpr static kFloatPow5Bitcount = 61;
  static constexpr uint64_t kFloatPow5Split[47] = {
      1152921504606846976u, 1441151880758558720u, 1801439850948198400u,
      2251799813685248000u, 1407374883553280000u, 1759218604441600000u,
      2199023255552000000u, 1374389534720000000u, 1717986918400000000u,
      2147483648000000000u, 1342177280000000000u, 1677721600000000000u,
      2097152000000000000u, 1310720000000000000u, 1638400000000000000u,
      2048000000000000000u, 1280000000000000000u, 1600000000000000000u,
      2000000000000000000u, 1250000000000000000u, 1562500000000000000u,
      1953125000000000000u, 1220703125000000000u, 1525878906250000000u,
      1907348632812500000u, 1192092895507812500u, 1490116119384765625u,
      1862645149230957031u, 1164153218269348144u, 1455191522836685180u,
      1818989403545856475u, 2273736754432320594u, 1421085471520200371u,
      1776356839400250464u, 2220446049250313080u, 1387778780781445675u,
      1734723475976807094u, 2168404344971008868u, 1355252715606880542u,
      1694065894508600678u, 2117582368135750847u, 1323488980084844279u,
      1654361225106055349u, 2067951531382569187u, 1292469707114105741u,
      1615587133892632177u, 2019483917365790221u};

  static uint32_t Pow5Factor(uint32_t value) {
    uint32_t count = 0;
    for (;;) {
      const uint32_t q = value / 5;
      const uint32_t r = value % 5;
      if (r != 0) {
        break;
      }
      value = q;
      ++count;
    }
    return count;
  }

  // Returns true if value is divisible by 5^p.
  static bool multipleOfPowerOf5(const uint32_t value, const uint32_t p) {
    return Pow5Factor(value) >= p;
  }

  // Returns true if value is divisible by 2^p.
  static bool multipleOfPowerOf2(const uint32_t value, const uint32_t p) {
    return __builtin_ctz(value) >= p;
    // return (value & ((1u << p) - 1)) == 0;
  }

  // Returns e == 0 ? 1 : ceil(log_2(5^e)).
  static uint32_t Pow5Bits(const int32_t e) {
    return (uint32_t)(((e * 163391164108059ull) >> 46) + 1);
  }

  /*
   * \brief Multiply 32-bit and 64-bit -> 128 bit, then access the higher bits.
   */
  static uint32_t MulShift(const uint32_t x, const uint64_t y,
                           const int32_t shift) {
    // For 32-bit * 64-bit: x * y, it can be decomposed into:
    // x * (y_high + y_low) = (x * y_high) + (x * y_low)
    const uint32_t y_low = (uint32_t)(y);
    const uint32_t y_high = (uint32_t)(y >> 32);

    const uint64_t low = (uint64_t)x * y_low;
    const uint64_t high = (uint64_t)x * y_high;

    const uint64_t sum = (low >> 32) + high;
    const uint64_t shifted_sum = sum >> (shift - 32);

    return (uint32_t)shifted_sum;
  }

  /*
   * \brief floor(5^q/2*k) and shift
   */
  static uint32_t MulPow5InvDivPow2(const uint32_t m, const uint32_t q,
                                    const int32_t j) {
    return MulShift(m, kFloatPow5InvSplit[q], j);
  }

  /*
   * \brief floor(2^k/5^q) + 1 and shift
   */
  static uint32_t MulPow5divPow2(const uint32_t m, const uint32_t i,
                                 const int32_t j) {
    return MulShift(m, kFloatPow5Split[i], j);
  }

  // Returns floor(e * log_10(2)).
  static uint32_t log10Pow2(const int32_t e) {
    // The first value this approximation fails for is 2^1651 which is just
    // greater than 10^297.
    assert(e >= 0);
    assert(e <= 1 << 15);
    return (uint32_t)((((uint64_t)e) * 169464822037455ull) >> 49);
  }

  // Returns floor(e * log_10(5)).
  static uint32_t Log10Pow5(const int32_t e) {
    // The first value this approximation fails for is 5^2621 which is just
    // greater than 10^1832.
    assert(e >= 0);
    assert(e <= 1 << 15);
    return (uint32_t)((((uint64_t)e) * 196742565691928ull) >> 48);
  }
};

inline UnsignedFloatBase10
ShortestRepresentation(bool mantissa_low_is_trailing_zeros, bool vrIsTrailingZeros,
                       const bool acceptBounds, int32_t exponent_base10,
                       uint32_t mantissa10_low, uint32_t mantissa10_v,
                       uint32_t mantissa10_high) {
  int32_t removed = 0;
  uint32_t output;
  uint8_t last_removed_digit = 0;
  if (mantissa_low_is_trailing_zeros || vrIsTrailingZeros) {
    // General case, which happens rarely (~4.0%).
    while (mantissa10_high / 10 > mantissa10_low / 10) {
      mantissa_low_is_trailing_zeros &= mantissa10_low % 10 == 0;
      vrIsTrailingZeros &= last_removed_digit == 0;
      last_removed_digit = (uint8_t)(mantissa10_v % 10);
      mantissa10_v /= 10;
      mantissa10_high /= 10;
      mantissa10_low /= 10;
      ++removed;
    }

    if (mantissa_low_is_trailing_zeros) {
      while (mantissa10_low % 10 == 0) {
        vrIsTrailingZeros &= last_removed_digit == 0;
        last_removed_digit = (uint8_t)(mantissa10_v % 10);
        mantissa10_v /= 10;
        mantissa10_high /= 10;
        mantissa10_low /= 10;
        ++removed;
      }
    }

    if (vrIsTrailingZeros && last_removed_digit == 5 && mantissa10_v % 2 == 0) {
      // Round even if the exact number is .....50..0.
      last_removed_digit = 4;
    }
    // We need to take vr + 1 if vr is outside bounds or we need to round up.
    output = mantissa10_v + ((mantissa10_v == mantissa10_low &&
                              (!acceptBounds || !mantissa_low_is_trailing_zeros)) ||
                             last_removed_digit >= 5);
  } else {
    // Specialized for the common case (~96.0%). Percentages below are relative
    // to this. Loop iterations below (approximately): 0: 13.6%, 1: 70.7%,
    // 2: 14.1%, 3: 1.39%, 4: 0.14%, 5+: 0.01%
    while (mantissa10_high / 10 > mantissa10_low / 10) {
      last_removed_digit = (uint8_t)(mantissa10_v % 10);
      mantissa10_v /= 10;
      mantissa10_high /= 10;
      mantissa10_low /= 10;
      ++removed;
    }

    // We need to take vr + 1 if vr is outside bounds or we need to round up.
    output = mantissa10_v +
             (mantissa10_v == mantissa10_low || last_removed_digit >= 5);
  }
  const int32_t exp = exponent_base10 + removed;

  UnsignedFloatBase10 fd;
  fd.exponent = exp;
  fd.mantissa = output;
  return fd;
}

inline UnsignedFloatBase10 float2decimal(UnsignedFloatBase2 f) {
  int32_t exponent_base2;
  uint32_t mantissa_base2;
  if (f.exponent == 0) {
    // We subtract 2 so that the bounds computation has 2 additional bits.
    exponent_base2 = 1 - IEEE754::kFloatBias - IEEE754::kFloatMantissaBits - 2;
    mantissa_base2 = f.mantissa;
  } else {
    exponent_base2 = (int32_t)f.exponent - IEEE754::kFloatBias - IEEE754::kFloatMantissaBits - 2;
    mantissa_base2 = (1u << IEEE754::kFloatMantissaBits) | f.mantissa;
  }
  const bool even = (mantissa_base2 & 1) == 0;
  const bool acceptBounds = even;

  // Step 2: Determine the interval of valid decimal representations.
  const uint32_t mantissa_v = 4 * mantissa_base2;
  const uint32_t mantissa_high = 4 * mantissa_base2 + 2;
  // Implicit bool -> int conversion. True is 1, false is 0.
  const uint32_t mmShift = f.mantissa != 0 || f.exponent <= 1;
  const uint32_t mantissa_low = 4 * mantissa_base2 - 1 - mmShift;

  // Step 3: Convert to a decimal power base using 64-bit arithmetic.
  uint32_t mantissa10_v, mantissa10_high, mantissa10_low;
  int32_t exponent_base10;
  bool vmIsTrailingZeros = false;
  bool vrIsTrailingZeros = false;
  uint8_t lastRemovedDigit = 0;
  if (exponent_base2 >= 0) {
    const uint32_t q = PowerBaseComputer::log10Pow2(exponent_base2);
    exponent_base10 = (int32_t)q;
    const int32_t k = PowerBaseComputer::kFloatPow5InvBitcount + PowerBaseComputer::Pow5Bits(static_cast<int32_t>(q)) - 1;
    const int32_t i = -exponent_base2 + (int32_t)q + k;
    mantissa10_low = PowerBaseComputer::MulPow5InvDivPow2(mantissa_low, q, i);
    mantissa10_v =   PowerBaseComputer::MulPow5InvDivPow2(mantissa_v, q, i);
    mantissa10_high = PowerBaseComputer::MulPow5InvDivPow2(mantissa_high, q, i);

    if (q != 0 && (mantissa10_high - 1) / 10 <= mantissa10_low / 10) {
      // We need to know one removed digit even if we are not going to loop
      // below. We could use q = X - 1 above, except that would require 33 bits
      // for the result, and we've found that 32-bit arithmetic is faster even
      // on 64-bit machines.
      const int32_t l =
          PowerBaseComputer::kFloatPow5InvBitcount + PowerBaseComputer::Pow5Bits((int32_t)(q - 1)) - 1;
      lastRemovedDigit = (uint8_t)(
          PowerBaseComputer::MulPow5InvDivPow2(mantissa_v, q - 1, -exponent_base2 + (int32_t)q - 1 + l) % 10);
    }
    if (q <= 9) {
      // The largest power of 5 that fits in 24 bits is 5^10, but q <= 9 seems
      // to be safe as well. Only one of mp, mv, and mm can be a multiple of 5,
      // if any.
      if (mantissa_v % 5 == 0) {
        vrIsTrailingZeros = PowerBaseComputer::multipleOfPowerOf5(mantissa_v, q);
      } else if (acceptBounds) {
        vmIsTrailingZeros = PowerBaseComputer::multipleOfPowerOf5(mantissa_low, q);
      } else {
        mantissa10_high -= PowerBaseComputer::multipleOfPowerOf5(mantissa_high, q);
      }
    }
  } else {
    const uint32_t q = PowerBaseComputer::Log10Pow5(-exponent_base2);
    exponent_base10 = (int32_t)q + exponent_base2;
    const int32_t i = -exponent_base2 - (int32_t)q;
    const int32_t k = PowerBaseComputer::Pow5Bits(i) - PowerBaseComputer::kFloatPow5Bitcount;
    int32_t j = (int32_t)q - k;
    mantissa10_v = PowerBaseComputer::MulPow5divPow2(mantissa_v, (uint32_t)i, j);
    mantissa10_high = PowerBaseComputer::MulPow5divPow2(mantissa_high, (uint32_t)i, j);
    mantissa10_low = PowerBaseComputer::MulPow5divPow2(mantissa_low, (uint32_t)i, j);

    if (q != 0 && (mantissa10_high - 1) / 10 <= mantissa10_low / 10) {
      j = (int32_t)q - 1 - (PowerBaseComputer::Pow5Bits(i + 1) - PowerBaseComputer::kFloatPow5Bitcount);
      lastRemovedDigit =
          (uint8_t)(PowerBaseComputer::MulPow5divPow2(mantissa_v, (uint32_t)(i + 1), j) % 10);
    }
    if (q <= 1) {
      // {vr,vp,vm} is trailing zeros if {mv,mp,mm} has at least q trailing 0
      // bits. mv = 4 * m2, so it always has at least two trailing 0 bits.
      vrIsTrailingZeros = true;
      if (acceptBounds) {
        // mm = mv - 1 - mmShift, so it has 1 trailing 0 bit iff mmShift == 1.
        vmIsTrailingZeros = mmShift == 1;
      } else {
        // mp = mv + 2, so it always has at least one trailing 0 bit.
        --mantissa10_high;
      }
    } else if (q < 31) { // TODO(ulfjack): Use a tighter bound here.
      vrIsTrailingZeros = PowerBaseComputer::multipleOfPowerOf2(mantissa_v, q - 1);
    }
  }

  // Step 4: Find the shortest decimal representation in the interval of valid
  // representations.
  auto out = ShortestRepresentation(vmIsTrailingZeros, vrIsTrailingZeros, acceptBounds,
                                    exponent_base10, mantissa10_low, mantissa10_v, mantissa10_high);
  return out;
}

static inline uint32_t decimalLength9(const uint32_t v) {
  // Function precondition: v is not a 10-digit number.
  // (f2s: 9 digits are sufficient for round-tripping.)
  // (d2fixed: We print 9-digit blocks.)
  assert(v < 1000000000);
  if (v >= 100000000) {
    return 9;
  }
  if (v >= 10000000) {
    return 8;
  }
  if (v >= 1000000) {
    return 7;
  }
  if (v >= 100000) {
    return 6;
  }
  if (v >= 10000) {
    return 5;
  }
  if (v >= 1000) {
    return 4;
  }
  if (v >= 100) {
    return 3;
  }
  if (v >= 10) {
    return 2;
  }
  return 1;
}

static inline int to_chars_impl(UnsignedFloatBase10 v, const bool sign,
                                char *const result) {
  // Step 5: Print the decimal representation.
  int index = 0;
  if (sign) {
    result[index++] = '-';
  }

  uint32_t output = v.mantissa;
  const uint32_t out_length = decimalLength9(output);

  // Print the decimal digits.
  // The following code is equivalent to:
  // for (uint32_t i = 0; i < olength - 1; ++i) {
  //   const uint32_t c = output % 10; output /= 10;
  //   result[index + olength - i] = (char) ('0' + c);
  // }
  // result[index] = '0' + output % 10;
  uint32_t i = 0;
  while (output >= 10000) {
    const uint32_t c = output % 10000;
    output /= 10000;
    const uint32_t c0 = (c % 100) << 1;
    const uint32_t c1 = (c / 100) << 1;
    // This is used to speed up decimal digit generation by copying
    // pairs of digits into the final output.
    std::memcpy(result + index + out_length - i - 1, kItoaLut + c0, 2);
    std::memcpy(result + index + out_length - i - 3, kItoaLut + c1, 2);
    i += 4;
  }
  if (output >= 100) {
    const uint32_t c = (output % 100) << 1;
    output /= 100;
    std::memcpy(result + index + out_length - i - 1, kItoaLut + c, 2);
    i += 2;
  }
  if (output >= 10) {
    const uint32_t c = output << 1;
    // We can't use std::memcpy here: the decimal dot goes between these two digits.
    result[index + out_length - i] = kItoaLut[c + 1];
    result[index] = kItoaLut[c];
  } else {
    result[index] = (char)('0' + output);
  }

  // Print decimal point if needed.
  if (out_length > 1) {
    result[index + 1] = '.';
    index += out_length + 1;
  } else {
    ++index;
  }

  // Print the exponent.
  result[index++] = 'E';
  int32_t exp = v.exponent + (int32_t)out_length - 1;
  if (exp < 0) {
    result[index++] = '-';
    exp = -exp;
  }

  if (exp >= 10) {
    std::memcpy(result + index, kItoaLut + 2 * exp, 2);
    index += 2;
  } else {
    result[index++] = (char)('0' + exp);
  }

  return index;
}

inline uint32_t Float2Bits(const float f) {
  uint32_t bits = 0;
  std::memcpy(&bits, &f, sizeof(float));
  return bits;
}

inline int32_t f2s_buffered_n(float f, char * const result) {
  // Step 1: Decode the floating-point number, and unify normalized and
  // subnormal cases.
  const uint32_t bits = Float2Bits(f);
  UnsignedFloatBase2 uf;
  bool sign;
  IEEE754::Decode(f, &uf, &sign);

    // Case distinction; exit early for the easy cases.
  if (uf.exponent == ((1u << IEEE754::kFloatExponentBits) - 1u) ||
      (uf.exponent == 0 && uf.mantissa == 0)) {
    return SpecialStr(result, sign, uf.exponent, uf.mantissa);
  }

  const UnsignedFloatBase10 v = float2decimal(uf);
  return to_chars_impl(v, sign, result);
}

} // namespace nih

#endif